#!/bin/sh
## Information
## https://carlo-hamalainen.net/2007/12/11/installing-minion-pro-fonts/ #KD: updated

## http://www.ctan.org/tex-archive/fonts/mnsymbol/

## 0.1: Install LCDF Typetools
## http://www.lcdf.org/type/
## If you use Homebrew (http://mxcl.github.com/homebrew/), then uncomment: 
#brew install lcdf-typetools 

## 0.2: If ~/tmp doesn't exist, create it.
mkdir ~/tmp

## Destination. System wide is best in recent MacTeX releases:  
DEST=`kpsexpand '$TEXMFLOCAL'`

## Downloader:
DOWNLOAD="curl -L -O"

## Directory where minion fonts may be found:
##KD: I didn't have any fonts in /Library/Fonts, but did have some in this folder

MINIONSRC=/Applications/Adobe\ Acrobat\ ReaderDC.app/Contents/Resources/Resource/Font/ #KD
#MINIONSRC=~/tmp/minionsrc
#MINIONSRC=~/Library/Fonts

## Everything gets done in a temporary directory
cd ~/tmp

## 1: MnSymbol
## http://www.ctan.org/tex-archive/fonts/mnsymbol/
$DOWNLOAD http://mirror.ctan.org/fonts/mnsymbol.zip 

unzip mnsymbol
cd mnsymbol/tex

## Generates MnSymbol.sty
latex MnSymbol.ins

mkdir -p $DEST/tex/latex/MnSymbol/      \
    $DEST/fonts/source/public/MnSymbol/ \
    $DEST/doc/latex/MnSymbol/

cp -pv MnSymbol.sty $DEST/tex/latex/MnSymbol/MnSymbol.sty
cd .. # we were in mnsymbol/tex
cp -pv source/* $DEST/fonts/source/public/MnSymbol/
cp -pv MnSymbol.pdf README $DEST/doc/latex/MnSymbol/

mkdir -p $DEST/fonts/map/dvips/MnSymbol \
    $DEST/fonts/enc/dvips/MnSymbol      \
    $DEST/fonts/type1/public/MnSymbol   \
    $DEST/fonts/tfm/public/MnSymbol 
cp -pv enc/MnSymbol.map $DEST/fonts/map/dvips/MnSymbol/
cp -pv enc/*.enc $DEST/fonts/enc/dvips/MnSymbol/
cp -pv pfb/*.pfb $DEST/fonts/type1/public/MnSymbol/
cp -pv tfm/* $DEST/fonts/tfm/public/MnSymbol/

## Not strictly needed if DEST is in the home
## tree on OSX (~/Library ...), but will be needed otherwise
mktexlsr
updmap -sys --enable MixedMap MnSymbol.map

# $DOWNLOAD http://carlo-hamalainen.net/blog/myfiles/minionpro/mnsymbol-test.tex
# pdflatex mnsymbol-test.tex

## 2: MinionPro
mkdir -p ~/tmp/minionpro
cd ~/tmp/minionpro

# $DOWNLOAD http://mirrors.ctan.org/fonts/minionpro/enc-2.000.zip
# $DOWNLOAD http://mirrors.ctan.org/fonts/minionpro/metrics-base.zip
# $DOWNLOAD http://mirrors.ctan.org/fonts/minionpro/metrics-full.zip
# $DOWNLOAD http://mirrors.ctan.org/fonts/minionpro/scripts.zip

curl -L -O http://mirrors.ctan.org/fonts/minionpro/enc-2.000.zip
curl -L -O http://mirrors.ctan.org/fonts/minionpro/metrics-base.zip

##
## KD: This file isn't used, given the available fonts
##
# curl -L -O http://mirrors.ctan.org/fonts/minionpro/metrics-full.zip
curl -L -O http://mirrors.ctan.org/fonts/minionpro/scripts.zip


##
## KD:  Why is source.zip missing here? -- See  the README in
##  https://ctan.org/tex-archive/fonts/minionpro/
##


## This will make the otf directory, among other things.
unzip scripts.zip

cp -pv $MINIONSRC/Minion*otf otf/

## Generate the pfb files
## This step requires that the LCDF type tools are installed. (which you did above with brew)

./convert.sh

## Copy the pfb files to where they belong:
mkdir -p $DEST/fonts/type1/adobe/MinionPro
cp -pv pfb/*.pfb $DEST/fonts/type1/adobe/MinionPro

SRC=`pwd`
cd $DEST
unzip $SRC/enc-2.000.zip
unzip $SRC/metrics-base.zip
unzip $SRC/metrics-full.zip
cd $SRC

## Not strictly needed if DEST is in the home
## tree on OSX (~/Library ...), but will be needed otherwise

mktexlsr
updmap-sys --syncwithtrees --enable MixedMap MinionPro.map

## I found I also had to run
## > updmap-sys
## here

## Test:
# $DOWNLOAD https://s3.amazonaws.com/carlo-hamalainen.net/oldblog/stuff/myfiles/minionpro/mnsymbol-test.tex
# pdflatex minionpro-test.tex
